"""2 - correction in DARPS

Revision ID: 1ded5e83a809
Revises: 6cb908b86eee
Create Date: 2022-07-17 17:40:57.660639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ded5e83a809'
down_revision = '6cb908b86eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('darps_ID', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_info', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_ts', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_ts', sa.String(), nullable=True))
    op.drop_column('fpso', 'darps_2_tdma_2')
    op.drop_column('fpso', 'darps_1_info')
    op.drop_column('fpso', 'darps_1_tdma_1')
    op.drop_column('fpso', 'darps_1_tdma_2')
    op.drop_column('fpso', 'darps_2_tdma_1')
    op.drop_column('fpso', 'darps_2_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('darps_2_info', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma_1', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma_2', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma_1', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_info', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma_2', sa.VARCHAR(), nullable=True))
    op.drop_column('fpso', 'darps_2_ts')
    op.drop_column('fpso', 'darps_1_ts')
    op.drop_column('fpso', 'darps_info')
    op.drop_column('fpso', 'darps_2_tdma')
    op.drop_column('fpso', 'darps_1_tdma')
    op.drop_column('fpso', 'darps_ID')
    # ### end Alembic commands ###
