"""1 - db init

Revision ID: 6cb908b86eee
Revises: 
Create Date: 2022-07-17 17:07:13.995876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb908b86eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpso_owner', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fpso_name', sa.String(), nullable=True),
    sa.Column('fpso_basin', sa.String(), nullable=True),
    sa.Column('fpso_psn_lat_deg', sa.String(), nullable=True),
    sa.Column('fpso_psn_lat_min', sa.String(), nullable=True),
    sa.Column('fpso_psn_lat_sec', sa.String(), nullable=True),
    sa.Column('fpso_psn_lat_NS', sa.String(), nullable=True),
    sa.Column('fpso_psn_long_deg', sa.String(), nullable=True),
    sa.Column('fpso_psn_long_min', sa.String(), nullable=True),
    sa.Column('fpso_psn_long_sec', sa.String(), nullable=True),
    sa.Column('fpso_psn_long_WE', sa.String(), nullable=True),
    sa.Column('fpso_hdg', sa.String(), nullable=True),
    sa.Column('fpso_disch_rate', sa.String(), nullable=True),
    sa.Column('fpso_vhf', sa.String(), nullable=True),
    sa.Column('fpso_email_1', sa.String(), nullable=True),
    sa.Column('fpso_email_2', sa.String(), nullable=True),
    sa.Column('fpso_email_3', sa.String(), nullable=True),
    sa.Column('fpso_email_4', sa.String(), nullable=True),
    sa.Column('fpso_email_5', sa.String(), nullable=True),
    sa.Column('cargo_name', sa.String(), nullable=True),
    sa.Column('cargo_API', sa.String(), nullable=True),
    sa.Column('cargo_dens', sa.String(), nullable=True),
    sa.Column('cargo_temp', sa.String(), nullable=True),
    sa.Column('cargo_line_displ', sa.String(), nullable=True),
    sa.Column('cargo_Hose_Flush', sa.String(), nullable=True),
    sa.Column('cargo_info', sa.String(), nullable=True),
    sa.Column('darps_1_tdma_1', sa.String(), nullable=True),
    sa.Column('darps_1_tdma_2', sa.String(), nullable=True),
    sa.Column('darps_1_info', sa.String(), nullable=True),
    sa.Column('darps_2_tdma_1', sa.String(), nullable=True),
    sa.Column('darps_2_tdma_2', sa.String(), nullable=True),
    sa.Column('darps_2_info', sa.String(), nullable=True),
    sa.Column('artemis_address_code', sa.String(), nullable=True),
    sa.Column('artemis_freq_pair', sa.String(), nullable=True),
    sa.Column('artemis_info', sa.String(), nullable=True),
    sa.Column('fanbeam_info', sa.String(), nullable=True),
    sa.Column('radius_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpso_fpso_name'), 'fpso', ['fpso_name'], unique=True)
    op.create_index(op.f('ix_fpso_fpso_owner'), 'fpso', ['fpso_owner'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_surname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_blog', sa.String(), nullable=True),
    sa.Column('user_password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_since', sa.DateTime(), nullable=True),
    sa.Column('user_last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_blog'), 'user', ['user_blog'], unique=False)
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    op.create_index(op.f('ix_user_user_surname'), 'user', ['user_surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('favorite',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fpso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fpso_id'], ['fpso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_user_blog'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_fpso_fpso_owner'), table_name='fpso')
    op.drop_index(op.f('ix_fpso_fpso_name'), table_name='fpso')
    op.drop_table('fpso')
    # ### end Alembic commands ###
