"""3 - added aft station

Revision ID: 731bd0ff23df
Revises: 1ded5e83a809
Create Date: 2022-07-17 19:49:33.212782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731bd0ff23df'
down_revision = '1ded5e83a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('cargo_line_displ_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('cargo_Hose_Flush_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('cargo_line_displ_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('cargo_Hose_Flush_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_ID_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_info_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_ts_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_ts_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_ID_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_info_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_ts_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_ts_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_address_code_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_freq_pair_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_info_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('fanbeam_info_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('radius_info_fwd', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_address_code_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_freq_pair_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_info_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('fanbeam_info_aft', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('radius_info_aft', sa.String(), nullable=True))
    op.drop_column('fpso', 'artemis_info')
    op.drop_column('fpso', 'darps_2_ts')
    op.drop_column('fpso', 'darps_1_tdma')
    op.drop_column('fpso', 'artemis_address_code')
    op.drop_column('fpso', 'artemis_freq_pair')
    op.drop_column('fpso', 'radius_info')
    op.drop_column('fpso', 'darps_2_tdma')
    op.drop_column('fpso', 'darps_1_ts')
    op.drop_column('fpso', 'fanbeam_info')
    op.drop_column('fpso', 'darps_ID')
    op.drop_column('fpso', 'cargo_line_displ')
    op.drop_column('fpso', 'darps_info')
    op.drop_column('fpso', 'cargo_Hose_Flush')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('cargo_Hose_Flush', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_info', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('cargo_line_displ', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_ID', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('fanbeam_info', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_ts', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_tdma', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('radius_info', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_freq_pair', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_address_code', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_1_tdma', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('darps_2_ts', sa.VARCHAR(), nullable=True))
    op.add_column('fpso', sa.Column('artemis_info', sa.VARCHAR(), nullable=True))
    op.drop_column('fpso', 'radius_info_aft')
    op.drop_column('fpso', 'fanbeam_info_aft')
    op.drop_column('fpso', 'artemis_info_aft')
    op.drop_column('fpso', 'artemis_freq_pair_aft')
    op.drop_column('fpso', 'artemis_address_code_aft')
    op.drop_column('fpso', 'radius_info_fwd')
    op.drop_column('fpso', 'fanbeam_info_fwd')
    op.drop_column('fpso', 'artemis_info_fwd')
    op.drop_column('fpso', 'artemis_freq_pair_fwd')
    op.drop_column('fpso', 'artemis_address_code_fwd')
    op.drop_column('fpso', 'darps_2_ts_aft')
    op.drop_column('fpso', 'darps_1_ts_aft')
    op.drop_column('fpso', 'darps_info_aft')
    op.drop_column('fpso', 'darps_2_tdma_aft')
    op.drop_column('fpso', 'darps_1_tdma_aft')
    op.drop_column('fpso', 'darps_ID_aft')
    op.drop_column('fpso', 'darps_2_ts_fwd')
    op.drop_column('fpso', 'darps_1_ts_fwd')
    op.drop_column('fpso', 'darps_info_fwd')
    op.drop_column('fpso', 'darps_2_tdma_fwd')
    op.drop_column('fpso', 'darps_1_tdma_fwd')
    op.drop_column('fpso', 'darps_ID_fwd')
    op.drop_column('fpso', 'cargo_Hose_Flush_aft')
    op.drop_column('fpso', 'cargo_line_displ_aft')
    op.drop_column('fpso', 'cargo_Hose_Flush_fwd')
    op.drop_column('fpso', 'cargo_line_displ_fwd')
    # ### end Alembic commands ###
