"""remark table

Revision ID: 7b0ec1c0e189
Revises: 8680c108f4ed
Create Date: 2026-04-11 01:53:57.845273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0ec1c0e189'
down_revision = '8680c108f4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fpso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fpso_id'], ['fpso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remark_timestamp'), 'remark', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remark_timestamp'), table_name='remark')
    op.drop_table('remark')
    # ### end Alembic commands ###
