"""Add img to the data base

Revision ID: 8680c108f4ed
Revises: bffe7117bd8f
Create Date: 2022-07-27 21:57:12.230539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8680c108f4ed'
down_revision = 'bffe7117bd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('fpso_img_name', sa.String(), nullable=True))
    op.add_column('fpso', sa.Column('fpso_remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fpso', 'fpso_remarks')
    op.drop_column('fpso', 'fpso_img_name')
    # ### end Alembic commands ###
