"""3 -  Add BSW

Revision ID: bffe7117bd8f
Revises: 731bd0ff23df
Create Date: 2022-07-18 17:28:55.053388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffe7117bd8f'
down_revision = '731bd0ff23df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpso', sa.Column('cargo_bsw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fpso', 'cargo_bsw')
    # ### end Alembic commands ###
