"""post table update

Revision ID: f445ed2490d8
Revises: f6f9ad8bc6e9
Create Date: 2026-04-17 23:51:11.891986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f445ed2490d8'
down_revision = 'f6f9ad8bc6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('blog_Title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'blog_Title')
    # ### end Alembic commands ###
